server:
  port: 8080
spring:
  application:
    name: accounts
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb  #jdbc:databasetype://server:port/schemaName
    # driverClassName: org..Driver
    username: root
    password: root
  jpa:
    # database-platform: org.hibernate.dialect.H2Dialect
    # hibernate:
    #   ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always  #In case of other database except the h2embedded one the spring expects table will be there so we added this
                    #this tells to springboot/JPA to excute the command present in resources/schema.sql and there we have
                    #written IF NOT EXIST means that create table comman will only execute if table is not present.
  config:
    import:
    - "optional:configserver:http://localhost:8071"
 



  profiles:
    active:
      - "prod"  #by default our acounts project will start with prod profile. we have application name and using same application name it'll look for profile in spring cloud config server

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"   #include all rest endpoint. we can mention refresh api alone but going for all.
                    #for only refresh endpoint, we can mention "refresh". it'll expose only refres endpoint
                    # of actuator