#Start with a base image containing Java runtime
FROM openjdk:21-jdk-slim


# MAINTAINER instruction is deprecated in favor of using label
# MAINTAINER eazybytes.com
#Information around who maintains the image
LABEL "Manis"

# Add the application's jar to the image
COPY target/accountsMicroservice.jar accountsMicroservice.jar

# execute the application
ENTRYPOINT ["java", "-jar", "accountsMicroservice.jar"]