spring:
  application:
    name: eurekaserver
  config:
    import: "optional:configserver:http://localhost:8071"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true #enabled for actuator
    liveness-state:
      enabled: true #enbale to check for actuator
  endpoint:
    shutdown:
      enabled: true # Enable graceful shutdown via REST API
    health:
      probes:
        enabled: true #enabled to check readiness and liveness through rest endpoints

  metrics:  #for metics monitoring for micrometer, grafana, prometheus. we are telling to group all the metrics related to this application under the application name. for example group all metrics related to accoutns MS under the application name accounts.
    tags:
      application: ${spring.application.name}