apiVersion: 1 #Standard we need to follow

deleteDatasources: #delete existing datasource if any existing when we run the docker-compose
  - name: Prometheus
  - name: Loki
  # - name: Tempo

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus #unique id for this connectiion
    url: http://prometheus:9090  #url where prometheus going to start. In docker-compose we have add port as 9090 so here we need to mention that.
    access: proxy
    orgId: 1
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
  # - name: Tempo
  #   type: tempo
  #   uid: tempo
  #   url: http://tempo:3100
  #   access: proxy
  #   orgId: 1
  #   basicAuth: false
  #   isDefault: false
  #   version: 1
  #   editable: true
  #   jsonData:
  #     httpMethod: GET
  #     serviceMap:
  #       datasourceUid: 'prometheus'
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    editable: true
    url: http://gateway:3100 #url where loki going to start. In docker-compose we have add port as 3100 so here we need to mention that.
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "\\[.+,(.+),.+\\]"
          name: TraceID
          url: '$${__value.raw}'
    secureJsonData:
      httpHeaderValue1: "tenant1"